= Common Programming Concepts
William <william@mrjaeger.net>
:stem: latexmath
:imagesdir: .assets/images
:source-highlighter: highlight.js
:toc:

== Variables

=== Declaration & Initialization

Variables are declared using the 'let' keyword and immutable by default. +
Values can be initialized at declaration or later in the code.

[source,rust]
----
include::./variables/src/main.rs[tag=declaration]
----

=== mutability

'mut' is used to make a variable mutable.

[source,rust]
----
include::variables/src/main.rs[tag=mutability]
----

=== Constants

Constants are declared using the 'const' keyword are immutable. +
They can not be made mutable.
Adding 'mut' will result in a compile time error.

[source,rust]
----
include::variables/src/main.rs[tag=constants-a]

main() {
include::variables/src/main.rs[tag=constants-b]
}
----

=== shadowing

Shadowing is the declaration of new variable using the name of a preexisting variable. +
The compiler identifies the second variable by the name until it leaves the scope or the second variable shadowed by another

[source,rust]
----
include::variables/src/main.rs[tags=mutability;shadowing]
----

== Data Types

=== Scalar Types

This represent single values.

Rust four primary scalar Types:

* integers
* floating-point
* numbers
* Booleans
* characters

==== Integer Types

|===
|Length |signed |unsigned

|8-bit
|i8
|u8

|16-bit
|i16
|u16

|32-bit
|i32
|u32

|64-bit
|i64
|u64

|128-bit
|i128
|u128

|arch
|isize
|usize
|===

Each signed variant can store numbers from -(2^n - 1^) to 2^n - 1^ - 1 inclusive, where n is the number of bits that variant uses. So an `i8` can store numbers from -(2^7^) to 2^7^ - 1, which equals -128 to 127. Unsigned variants, `u8`, can store numbers from 0 to 2^n^ - 1, so a u8 can store numbers from 0 to 2^8^ - 1, which equals 0 to 255.

Additionally, the isize and usize types depend on the architecture of the computer your program is running on, which is denoted in the table as “arch”: 64 bits if you're on a 64-bit architecture and 32 bits if you're on a 32-bit architecture.

.Integer Literals
****

|===
|Number Literal |Format |Example |Decimal Value

|Decimal
|#
|98_654
|98,000

|Hex
|0x#
|0xff
|255

|Octal
|0o#
|0o77
|63

|Binary
|0b#
|0b1111_0000
|240

|Byte (`u8` only)
|b'#'
|b'A'
|
|===

Number literals that can be multiple numeric types allow a type suffix, such as `57u8`, to designate the type. Number literals can also use `_` as a visual separator to make the number easier to read, such as `1_000`, which will have the same value as if you had specified 1000.

****

.Integer Overflow
****
****

==== Floating-Point Types

==== Numeric Operations

==== The Boolean Type

==== The Character Type

=== Compound Types

==== The Tuple Type

==== The Array Type
