= Common Programming Concepts
William <william@mrjaeger.net>
:stem: latexmath
:imagesdir: .assets/images
:source-highlighter: highlight.js
:toc:

== Variables

=== Declaration & Initialization

Variables are declared using the 'let' keyword and immutable by default. +
Values can be initialized at declaration or later in the code.

[source,rust]
----
include::./variables/src/main.rs[tag=declaration]
----

=== mutability

'mut' is used to make a variable mutable.

[source,rust]
----
include::variables/src/main.rs[tag=mutability]
----

=== Constants

Constants are declared using the 'const' keyword are immutable. +
They can not be made mutable.
Adding 'mut' will result in a compile time error.

[source,rust]
----
include::variables/src/main.rs[tag=constants-a]

main() {
include::variables/src/main.rs[tag=constants-b]
}
----

=== shadowing

Shadowing is the declaration of new variable using the name of a preexisting variable. +
The compiler identifies the second variable by the name until it leaves the scope or the second variable shadowed by another

[source,rust]
----
include::variables/src/main.rs[tags=mutability;shadowing]
----

== Data Types

=== Scalar Types

This represent single values.

Rust four primary scalar Types: integers, floating-point, numbers, Booleans, characters

==== Integer Types

Thr default is `i32`.

|===
|Length |signed |unsigned

|8-bit
|i8
|u8

|16-bit
|i16
|u16

|32-bit
|i32
|u32

|64-bit
|i64
|u64

|128-bit
|i128
|u128

|arch
|isize
|usize
|===

Each signed variant can store numbers from -(2^n - 1^) to 2^n - 1^ - 1 inclusive, where n is the number of bits that variant uses. So an `i8` can store numbers from -(2^7^) to 2^7^ - 1, which equals -128 to 127. Unsigned variants, `u8`, can store numbers from 0 to 2^n^ - 1, so a u8 can store numbers from 0 to 2^8^ - 1, which equals 0 to 255.

Additionally, the isize and usize types depend on the architecture of the computer your program is running on, which is denoted in the table as “arch”: 64 bits if you're on a 64-bit architecture and 32 bits if you're on a 32-bit architecture.

.Integer Literals
****

|===
|Number Literal |Format |Example |Decimal Value

|Decimal
|#
|98_654
|98,000

|Hex
|0x#
|0xff
|255

|Octal
|0o#
|0o77
|63

|Binary
|0b#
|0b1111_0000
|240

|Byte (`u8` only)
|b'#'
|b'A'
|
|===

Number literals that can be multiple numeric types allow a type suffix, such as `57u8`, to designate the type. Number literals can also use `_` as a visual separator to make the number easier to read, such as `1_000`, which will have the same value as if you had specified 1000.

****

.Integer Overflow
****

Let's say you have a variable of type u8 that can hold values between 0 and 255. If you try to change the variable to a value outside that range, such as 256, integer overflow will occur, which can result in one of two behaviors. When you're compiling in debug mode, Rust includes checks for integer overflow that cause your program to panic at runtime if this behavior occurs. Rust uses the term panicking when a program exits with an error; we'll discuss panics in more depth in the “Unrecoverable Errors with panic!” section in Chapter 9.

When you're compiling in release mode with the --release flag, Rust does not include checks for integer overflow that cause panics. Instead, if overflow occurs, Rust performs two's complement wrapping. In short, values greater than the maximum value the type can hold “wrap around” to the minimum of the values the type can hold. In the case of a u8, the value 256 becomes 0, the value 257 becomes 1, and so on. The program won't panic, but the variable will have a value that probably isn't what you were expecting it to have. Relying on integer overflow's wrapping behavior is considered an error.

 To explicitly handle the possibility of overflow, you can use these families of methods provided by the standard library for primitive numeric types:
    Wrap in all modes with the wrapping_* methods, such as wrapping_add.
    Return the None value if there is overflow with the checked_* methods.
    Return the value and a boolean indicating whether there was overflow with the overflowing_* methods.
    Saturate at the value's minimum or maximum values with the saturating_* methods.


****

==== Floating-Point Types

Floating-point numbers are represented according to the IEEE-754 standard. The f32 type is a single-precision float, and f64 has double precision.

The default type is f64 because on modern CPUs, it’s roughly the same speed as f32 but is capable of more precision. All floating-point types are signed.

[source,rust]
----
include::data-types/src/main.rs[tag=floating-point]
----

==== Numeric Operations

==== The Boolean Type

==== The Character Type

=== Compound Types

==== The Tuple Type

==== The Array Type
