= Notes
William <william@mrjaeger.net>
:stem: latexmath
:imagesdir: .assets/images
:source-highlighter: highlight.js
:toc:

== Variables

=== Declaration & Initialization

Variables are declared using the 'let' keyword and immutable by default. +
Values can be initialized at declaration or later in the code.

[source,rust]
----
include::./variables/src/main.rs[tag=declaration]
----

=== mutability

'mut' is used to make a variable mutable.

[source,rust]
----
include::variables/src/main.rs[tag=mutability]
----

=== Constants

Constants are declared using the 'const' keyword are immutable. +
They can not be made mutable.
Adding 'mut' will result in a compile time error.

[source,rust]
----
include::variables/src/main.rs[tag=constants-a]

main() {
include::variables/src/main.rs[tag=constants-b]
}
----

=== shadowing

Shadowing is the declaration of new variable using the name of a preexisting variable. +
The compiler identifies the second variable by the name until it leaves the scope or the second variable shadowed by another

[source,rust]
----
include::variables/src/main.rs[tags=mutability;shadowing]
----

== Data Types

=== Scalar Types

This represent single values.

Rust four primary scalar Types:

* integers
* floating-point
* numbers
* Booleans
* characters

==== Integer Types

|===
|Length |signed |unsigned

|8-bit
|i8
|u8

|16-bit
|i16
|u16

|32-bit
|i32
|u32

|64-bit
|i64
|u64

|128-bit
|i128
|u128

|arch
|isize
|usize
|===

.Integer Overflow
****
****

==== Floating-Point Types

==== Numeric Operations

==== The Boolean Type

==== The Character Type

=== Compound Types

==== The Tuple Type

==== The Array Type
