[package]
name = "snake"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m = "*"
cortex-m-rt = "*"
microbit = { version = "*", package = "microbit-v2" }
panic-halt = "*"
rtt-target = { version = "*", features = ["cortex-m"] }
panic-rtt-target = { version = "*", features = ["cortex-m"] }
